---
- name: Deinstall Packages
  apt:
    name: [ 'cloud-init' ]
    update_cache:     "{{ apt_proxy.update_repo | default(no) }}"
    cache_valid_time: "{{ apt_proxy.update_cache | default(0) }}"
    state: absent 
  become: yes
  when: 
    - ansible_distribution == "Debian"

- name: Install Packages
  apt:
    name: [ 'vim', 
            'vim-scripts', 
            'vim-doc', 
            'keyboard-configuration', 
            'debian-keyring', 
            'debian-archive-keyring', 
            'debian-ports-archive-keyring', 
            'dnsutils', 
            'figlet', 
            'tmux', 
            'jq' ]
    update_cache:     "{{ apt_proxy.update_repo | default(no) }}"
    cache_valid_time: "{{ apt_proxy.update_cache | default(0) }}"
    state: present 
  become: yes
  when: 
    - ansible_distribution == "Debian"