---
- name: Deinstall graphical interface 
  include_role: 
    name: setenv_gui-setup
  when:
    - enviroment is defined
    - enviroment.gui_system is defined
    - not enviroment.gui_system

- name: Install and deinstall defaults 
  include_tasks: install.yml
